---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: eap-app
  name: eap-app
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: eap-app
    weight: 100
  wildcardPolicy: None
